# Generated by Django 5.2.4 on 2026-09-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financeiro.transferencia'),
        ),
    ]
